In [3]:
import numpy as np
import math
import sklearn.metrics
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0001):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                 if R[i][j] > 0:
                     eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                     for k in range(K):
                        P[i][k] = P[i][k] + alpha * 2 * eij * Q[k][j]
                        Q[k][j] = Q[k][j] + alpha * 2 * eij * P[i][k]
        return P, Q.T
R = [[0,5,4,2, 1],[1,0,0,5, 3], [1,4,4,1, 0],[0,0,2, 0, 2],[3,1,1,0, 0] ]
R = np.array(R)
N = len(R)
M = len(R[0])
K = 1
P = np.random.rand(N,K)
Q = np.random.rand(M,K)
nP, nQ = matrix_factorization(R, P, Q, K)
nR = np.dot(nP, nQ.T)
print("Name : Athul Gopinath")
print("Roll No: CB.SC.I5DAS21018")
print(nR)

Name : Athul Gopinath
Roll No: CB.SC.I5DAS21018
[[0.00520502 0.01842102 0.03443556 0.03356968 0.0097163 ]
 [0.12467679 0.44124176 0.82484082 0.80410014 0.23273628]
 [0.1020978  0.36133278 0.67546197 0.65847743 0.19058769]
 [0.06477852 0.22925669 0.42856386 0.4177876  0.12092316]
 [0.02258949 0.07994614 0.14944832 0.14569043 0.04216819]]
